### ISSUE TITLE
GoWebDav可以安装，无法启动，希望修复

### ISSUE THREAD

**Issue by cnfepa** [1715173329/gowebdav#4]
可以在istore安装，但是无法启动，
使用的openwrt版本为：OpenWrt Ipv6-Plus-Vip-R2023.05.06 by Sirpdboy

以前使用老版本时可以使用gowebdav，不知道什么时候更新openwrt后，换过多个版本，Gowebdav都无法启动使用，希望修复，谢谢。

**Comment by cnfepa** [comment]
已经向istore团队反映此问题，已经修复此BUG，谢谢。

**Comment by 1715173329** [comment]
无关 issue。
